version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  realtorapp:
    image: realtorapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
